apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job1
spec:
  template:
    spec:
      containers:
        - name: spark
          image: afrogrit/mlops101-spark-job1:latest
      restartPolicy: Never
