name: Model Training Pipeline
on:
  push:
    paths:
      - "ml/models/**"
      - "pipelines/**"
      - ".github/workflows/model-pipeline.yaml"

jobs:
  train-model:
    runs-on: [self-hosted]
    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kfp==2.7.0 yamllint

      - name: Compile pipeline
        run: |
          dsl-compile --py pipelines/training_pipeline.py --output pipelines/training_pipeline.yaml

      - name: Submit to Kubeflow
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          KUBEFLOW_ENDPOINT: ${{ secrets.KUBEFLOW_ENDPOINT }}
        run: |
          # Configure cluster access
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config

          # Submit pipeline
          kfp --endpoint $KUBEFLOW_ENDPOINT pipeline upload \
            -p mlops101-pipeline \
            pipelines/training_pipeline.yaml
